name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: push
jobs:
  test-actions:
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.repository }} repository
        uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
      - run: yarn export
      - name: setting for deploy
        run: cd out && echo 'azisong.com' > CNAME && touch .nojekyll
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
      - run: echo "ğŸ This job's status is ${{ job.status }}."
